source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'KGModal', '~> 1.2.0'
pod 'MGSwipeTableCell'
pod 'FMDB'
pod 'RSBarcodes_Swift', '~> 0.1.9'
pod 'JLToast', '~> 1.4'
pod 'SCRecorder'
pod 'TSMessages'
pod 'Toast-Swift', '~> 1.3.0'
pod 'SDWebImage', '~>3.8'
pod 'DBAlertController'